pub mod adapter_trait;
mod adapters;
mod attribution;
mod bench;
mod chau7;
mod collector;
mod crash_reports;
mod engine;
mod friction;
mod history;
mod identity;
mod pipeline;

pub use aetower_attribution::build_entities;
pub use aetower_collector::{Collector, RawHostSample, RawProcessSample, RawSnapshot};
pub use aetower_friction::apply as apply_friction;
pub use aetower_history::History;
pub use aetower_identity::{EntitySeed, IdentityMap, resolve as resolve_identity};
pub use bench::{BenchmarkConfig, BenchmarkReport, BenchmarkStats, run_benchmark};
pub use engine::{Engine, RuntimeCollectionSettings};
pub use pipeline::{EntityPipelineOutput, run_entity_pipeline};
