[workspace]
members = [
  "crates/aetower-model",
  "crates/aetower-core",
  "crates/aetower-ffi",
  "crates/uniffi-bindgen-swift",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.29"
anyhow = "1"
parking_lot = "0.12"
uniffi = { version = "0.28", features = ["cli"] }
