[package]
name = "aetower-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
aetower-core = { path = "../aetower-core" }
aetower-model = { path = "../aetower-model" }
serde_json.workspace = true
uniffi.workspace = true
