// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(aetower_ffiFFI)
import aetower_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_aetower_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_aetower_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol MonitorEngineProtocol : AnyObject {
    
    func clearFrontmostAppState() 
    
    func configureChromiumEndpoint(endpoint: String?) 
    
    func configureDockerSocketPath(socketPath: String) 
    
    func configurePrivilegedHelper(helperPath: String?, enabled: Bool) 
    
    func latestSnapshot()  -> SystemSnapshot
    
    func setCapabilityState(kind: CapabilityKind, state: CapabilityState, detailOverride: String?) 
    
    func updateFrontmostAppState(state: FrontmostAppState) 
    
}

open class MonitorEngine:
    MonitorEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_aetower_ffi_fn_clone_monitorengine(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_aetower_ffi_fn_constructor_monitorengine_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_aetower_ffi_fn_free_monitorengine(pointer, $0) }
    }

    

    
open func clearFrontmostAppState() {try! rustCall() {
    uniffi_aetower_ffi_fn_method_monitorengine_clear_frontmost_app_state(self.uniffiClonePointer(),$0
    )
}
}
    
open func configureChromiumEndpoint(endpoint: String?) {try! rustCall() {
    uniffi_aetower_ffi_fn_method_monitorengine_configure_chromium_endpoint(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(endpoint),$0
    )
}
}
    
open func configureDockerSocketPath(socketPath: String) {try! rustCall() {
    uniffi_aetower_ffi_fn_method_monitorengine_configure_docker_socket_path(self.uniffiClonePointer(),
        FfiConverterString.lower(socketPath),$0
    )
}
}
    
open func configurePrivilegedHelper(helperPath: String?, enabled: Bool) {try! rustCall() {
    uniffi_aetower_ffi_fn_method_monitorengine_configure_privileged_helper(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(helperPath),
        FfiConverterBool.lower(enabled),$0
    )
}
}
    
open func latestSnapshot() -> SystemSnapshot {
    return try!  FfiConverterTypeSystemSnapshot.lift(try! rustCall() {
    uniffi_aetower_ffi_fn_method_monitorengine_latest_snapshot(self.uniffiClonePointer(),$0
    )
})
}
    
open func setCapabilityState(kind: CapabilityKind, state: CapabilityState, detailOverride: String?) {try! rustCall() {
    uniffi_aetower_ffi_fn_method_monitorengine_set_capability_state(self.uniffiClonePointer(),
        FfiConverterTypeCapabilityKind.lower(kind),
        FfiConverterTypeCapabilityState.lower(state),
        FfiConverterOptionString.lower(detailOverride),$0
    )
}
}
    
open func updateFrontmostAppState(state: FrontmostAppState) {try! rustCall() {
    uniffi_aetower_ffi_fn_method_monitorengine_update_frontmost_app_state(self.uniffiClonePointer(),
        FfiConverterTypeFrontmostAppState.lower(state),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMonitorEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MonitorEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MonitorEngine {
        return MonitorEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MonitorEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MonitorEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MonitorEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMonitorEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> MonitorEngine {
    return try FfiConverterTypeMonitorEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMonitorEngine_lower(_ value: MonitorEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMonitorEngine.lower(value)
}


public struct AggregateMetrics {
    public var cpuPercent: Float
    public var memoryResidentBytes: UInt64
    public var virtualMemoryBytes: UInt64
    public var diskReadBps: UInt64
    public var diskWriteBps: UInt64
    public var networkReceiveBps: UInt64
    public var networkSendBps: UInt64
    public var processCount: UInt32
    public var isForeground: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cpuPercent: Float, memoryResidentBytes: UInt64, virtualMemoryBytes: UInt64, diskReadBps: UInt64, diskWriteBps: UInt64, networkReceiveBps: UInt64, networkSendBps: UInt64, processCount: UInt32, isForeground: Bool) {
        self.cpuPercent = cpuPercent
        self.memoryResidentBytes = memoryResidentBytes
        self.virtualMemoryBytes = virtualMemoryBytes
        self.diskReadBps = diskReadBps
        self.diskWriteBps = diskWriteBps
        self.networkReceiveBps = networkReceiveBps
        self.networkSendBps = networkSendBps
        self.processCount = processCount
        self.isForeground = isForeground
    }
}



extension AggregateMetrics: Equatable, Hashable {
    public static func ==(lhs: AggregateMetrics, rhs: AggregateMetrics) -> Bool {
        if lhs.cpuPercent != rhs.cpuPercent {
            return false
        }
        if lhs.memoryResidentBytes != rhs.memoryResidentBytes {
            return false
        }
        if lhs.virtualMemoryBytes != rhs.virtualMemoryBytes {
            return false
        }
        if lhs.diskReadBps != rhs.diskReadBps {
            return false
        }
        if lhs.diskWriteBps != rhs.diskWriteBps {
            return false
        }
        if lhs.networkReceiveBps != rhs.networkReceiveBps {
            return false
        }
        if lhs.networkSendBps != rhs.networkSendBps {
            return false
        }
        if lhs.processCount != rhs.processCount {
            return false
        }
        if lhs.isForeground != rhs.isForeground {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(cpuPercent)
        hasher.combine(memoryResidentBytes)
        hasher.combine(virtualMemoryBytes)
        hasher.combine(diskReadBps)
        hasher.combine(diskWriteBps)
        hasher.combine(networkReceiveBps)
        hasher.combine(networkSendBps)
        hasher.combine(processCount)
        hasher.combine(isForeground)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAggregateMetrics: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AggregateMetrics {
        return
            try AggregateMetrics(
                cpuPercent: FfiConverterFloat.read(from: &buf), 
                memoryResidentBytes: FfiConverterUInt64.read(from: &buf), 
                virtualMemoryBytes: FfiConverterUInt64.read(from: &buf), 
                diskReadBps: FfiConverterUInt64.read(from: &buf), 
                diskWriteBps: FfiConverterUInt64.read(from: &buf), 
                networkReceiveBps: FfiConverterUInt64.read(from: &buf), 
                networkSendBps: FfiConverterUInt64.read(from: &buf), 
                processCount: FfiConverterUInt32.read(from: &buf), 
                isForeground: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: AggregateMetrics, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.cpuPercent, into: &buf)
        FfiConverterUInt64.write(value.memoryResidentBytes, into: &buf)
        FfiConverterUInt64.write(value.virtualMemoryBytes, into: &buf)
        FfiConverterUInt64.write(value.diskReadBps, into: &buf)
        FfiConverterUInt64.write(value.diskWriteBps, into: &buf)
        FfiConverterUInt64.write(value.networkReceiveBps, into: &buf)
        FfiConverterUInt64.write(value.networkSendBps, into: &buf)
        FfiConverterUInt32.write(value.processCount, into: &buf)
        FfiConverterBool.write(value.isForeground, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAggregateMetrics_lift(_ buf: RustBuffer) throws -> AggregateMetrics {
    return try FfiConverterTypeAggregateMetrics.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAggregateMetrics_lower(_ value: AggregateMetrics) -> RustBuffer {
    return FfiConverterTypeAggregateMetrics.lower(value)
}


public struct CapabilitySnapshot {
    public var kind: CapabilityKind
    public var state: CapabilityState
    public var detail: String
    public var lastUpdatedMillis: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: CapabilityKind, state: CapabilityState, detail: String, lastUpdatedMillis: UInt64) {
        self.kind = kind
        self.state = state
        self.detail = detail
        self.lastUpdatedMillis = lastUpdatedMillis
    }
}



extension CapabilitySnapshot: Equatable, Hashable {
    public static func ==(lhs: CapabilitySnapshot, rhs: CapabilitySnapshot) -> Bool {
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        if lhs.detail != rhs.detail {
            return false
        }
        if lhs.lastUpdatedMillis != rhs.lastUpdatedMillis {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(kind)
        hasher.combine(state)
        hasher.combine(detail)
        hasher.combine(lastUpdatedMillis)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCapabilitySnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CapabilitySnapshot {
        return
            try CapabilitySnapshot(
                kind: FfiConverterTypeCapabilityKind.read(from: &buf), 
                state: FfiConverterTypeCapabilityState.read(from: &buf), 
                detail: FfiConverterString.read(from: &buf), 
                lastUpdatedMillis: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: CapabilitySnapshot, into buf: inout [UInt8]) {
        FfiConverterTypeCapabilityKind.write(value.kind, into: &buf)
        FfiConverterTypeCapabilityState.write(value.state, into: &buf)
        FfiConverterString.write(value.detail, into: &buf)
        FfiConverterUInt64.write(value.lastUpdatedMillis, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapabilitySnapshot_lift(_ buf: RustBuffer) throws -> CapabilitySnapshot {
    return try FfiConverterTypeCapabilitySnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapabilitySnapshot_lower(_ value: CapabilitySnapshot) -> RustBuffer {
    return FfiConverterTypeCapabilitySnapshot.lower(value)
}


public struct ComponentSnapshot {
    public var kind: ComponentKind
    public var title: String
    public var detail: String
    public var cpuPercent: Float
    public var memoryBytes: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: ComponentKind, title: String, detail: String, cpuPercent: Float, memoryBytes: UInt64) {
        self.kind = kind
        self.title = title
        self.detail = detail
        self.cpuPercent = cpuPercent
        self.memoryBytes = memoryBytes
    }
}



extension ComponentSnapshot: Equatable, Hashable {
    public static func ==(lhs: ComponentSnapshot, rhs: ComponentSnapshot) -> Bool {
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.detail != rhs.detail {
            return false
        }
        if lhs.cpuPercent != rhs.cpuPercent {
            return false
        }
        if lhs.memoryBytes != rhs.memoryBytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(kind)
        hasher.combine(title)
        hasher.combine(detail)
        hasher.combine(cpuPercent)
        hasher.combine(memoryBytes)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeComponentSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ComponentSnapshot {
        return
            try ComponentSnapshot(
                kind: FfiConverterTypeComponentKind.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                detail: FfiConverterString.read(from: &buf), 
                cpuPercent: FfiConverterFloat.read(from: &buf), 
                memoryBytes: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: ComponentSnapshot, into buf: inout [UInt8]) {
        FfiConverterTypeComponentKind.write(value.kind, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.detail, into: &buf)
        FfiConverterFloat.write(value.cpuPercent, into: &buf)
        FfiConverterUInt64.write(value.memoryBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComponentSnapshot_lift(_ buf: RustBuffer) throws -> ComponentSnapshot {
    return try FfiConverterTypeComponentSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComponentSnapshot_lower(_ value: ComponentSnapshot) -> RustBuffer {
    return FfiConverterTypeComponentSnapshot.lower(value)
}


public struct EntitySnapshot {
    public var entityId: String
    public var displayName: String
    public var bundleId: String?
    public var executablePath: String?
    public var entityKind: EntityKind
    public var metrics: AggregateMetrics
    public var friction: FrictionBreakdown
    public var components: [ComponentSnapshot]
    public var badges: [String]
    public var activeWindowTitle: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(entityId: String, displayName: String, bundleId: String?, executablePath: String?, entityKind: EntityKind, metrics: AggregateMetrics, friction: FrictionBreakdown, components: [ComponentSnapshot], badges: [String], activeWindowTitle: String?) {
        self.entityId = entityId
        self.displayName = displayName
        self.bundleId = bundleId
        self.executablePath = executablePath
        self.entityKind = entityKind
        self.metrics = metrics
        self.friction = friction
        self.components = components
        self.badges = badges
        self.activeWindowTitle = activeWindowTitle
    }
}



extension EntitySnapshot: Equatable, Hashable {
    public static func ==(lhs: EntitySnapshot, rhs: EntitySnapshot) -> Bool {
        if lhs.entityId != rhs.entityId {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.bundleId != rhs.bundleId {
            return false
        }
        if lhs.executablePath != rhs.executablePath {
            return false
        }
        if lhs.entityKind != rhs.entityKind {
            return false
        }
        if lhs.metrics != rhs.metrics {
            return false
        }
        if lhs.friction != rhs.friction {
            return false
        }
        if lhs.components != rhs.components {
            return false
        }
        if lhs.badges != rhs.badges {
            return false
        }
        if lhs.activeWindowTitle != rhs.activeWindowTitle {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(entityId)
        hasher.combine(displayName)
        hasher.combine(bundleId)
        hasher.combine(executablePath)
        hasher.combine(entityKind)
        hasher.combine(metrics)
        hasher.combine(friction)
        hasher.combine(components)
        hasher.combine(badges)
        hasher.combine(activeWindowTitle)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntitySnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EntitySnapshot {
        return
            try EntitySnapshot(
                entityId: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                bundleId: FfiConverterOptionString.read(from: &buf), 
                executablePath: FfiConverterOptionString.read(from: &buf), 
                entityKind: FfiConverterTypeEntityKind.read(from: &buf), 
                metrics: FfiConverterTypeAggregateMetrics.read(from: &buf), 
                friction: FfiConverterTypeFrictionBreakdown.read(from: &buf), 
                components: FfiConverterSequenceTypeComponentSnapshot.read(from: &buf), 
                badges: FfiConverterSequenceString.read(from: &buf), 
                activeWindowTitle: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: EntitySnapshot, into buf: inout [UInt8]) {
        FfiConverterString.write(value.entityId, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterOptionString.write(value.bundleId, into: &buf)
        FfiConverterOptionString.write(value.executablePath, into: &buf)
        FfiConverterTypeEntityKind.write(value.entityKind, into: &buf)
        FfiConverterTypeAggregateMetrics.write(value.metrics, into: &buf)
        FfiConverterTypeFrictionBreakdown.write(value.friction, into: &buf)
        FfiConverterSequenceTypeComponentSnapshot.write(value.components, into: &buf)
        FfiConverterSequenceString.write(value.badges, into: &buf)
        FfiConverterOptionString.write(value.activeWindowTitle, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntitySnapshot_lift(_ buf: RustBuffer) throws -> EntitySnapshot {
    return try FfiConverterTypeEntitySnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntitySnapshot_lower(_ value: EntitySnapshot) -> RustBuffer {
    return FfiConverterTypeEntitySnapshot.lower(value)
}


public struct FrictionBreakdown {
    public var totalScore: Float
    public var cpuScore: Float
    public var memoryScore: Float
    public var diskScore: Float
    public var foregroundBonus: Float
    public var reasons: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(totalScore: Float, cpuScore: Float, memoryScore: Float, diskScore: Float, foregroundBonus: Float, reasons: [String]) {
        self.totalScore = totalScore
        self.cpuScore = cpuScore
        self.memoryScore = memoryScore
        self.diskScore = diskScore
        self.foregroundBonus = foregroundBonus
        self.reasons = reasons
    }
}



extension FrictionBreakdown: Equatable, Hashable {
    public static func ==(lhs: FrictionBreakdown, rhs: FrictionBreakdown) -> Bool {
        if lhs.totalScore != rhs.totalScore {
            return false
        }
        if lhs.cpuScore != rhs.cpuScore {
            return false
        }
        if lhs.memoryScore != rhs.memoryScore {
            return false
        }
        if lhs.diskScore != rhs.diskScore {
            return false
        }
        if lhs.foregroundBonus != rhs.foregroundBonus {
            return false
        }
        if lhs.reasons != rhs.reasons {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(totalScore)
        hasher.combine(cpuScore)
        hasher.combine(memoryScore)
        hasher.combine(diskScore)
        hasher.combine(foregroundBonus)
        hasher.combine(reasons)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFrictionBreakdown: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FrictionBreakdown {
        return
            try FrictionBreakdown(
                totalScore: FfiConverterFloat.read(from: &buf), 
                cpuScore: FfiConverterFloat.read(from: &buf), 
                memoryScore: FfiConverterFloat.read(from: &buf), 
                diskScore: FfiConverterFloat.read(from: &buf), 
                foregroundBonus: FfiConverterFloat.read(from: &buf), 
                reasons: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: FrictionBreakdown, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.totalScore, into: &buf)
        FfiConverterFloat.write(value.cpuScore, into: &buf)
        FfiConverterFloat.write(value.memoryScore, into: &buf)
        FfiConverterFloat.write(value.diskScore, into: &buf)
        FfiConverterFloat.write(value.foregroundBonus, into: &buf)
        FfiConverterSequenceString.write(value.reasons, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrictionBreakdown_lift(_ buf: RustBuffer) throws -> FrictionBreakdown {
    return try FfiConverterTypeFrictionBreakdown.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrictionBreakdown_lower(_ value: FrictionBreakdown) -> RustBuffer {
    return FfiConverterTypeFrictionBreakdown.lower(value)
}


public struct FrontmostAppState {
    public var appName: String
    public var bundleId: String?
    public var executablePath: String?
    public var windowTitle: String?
    public var capturedAtMillis: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(appName: String, bundleId: String?, executablePath: String?, windowTitle: String?, capturedAtMillis: UInt64) {
        self.appName = appName
        self.bundleId = bundleId
        self.executablePath = executablePath
        self.windowTitle = windowTitle
        self.capturedAtMillis = capturedAtMillis
    }
}



extension FrontmostAppState: Equatable, Hashable {
    public static func ==(lhs: FrontmostAppState, rhs: FrontmostAppState) -> Bool {
        if lhs.appName != rhs.appName {
            return false
        }
        if lhs.bundleId != rhs.bundleId {
            return false
        }
        if lhs.executablePath != rhs.executablePath {
            return false
        }
        if lhs.windowTitle != rhs.windowTitle {
            return false
        }
        if lhs.capturedAtMillis != rhs.capturedAtMillis {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(appName)
        hasher.combine(bundleId)
        hasher.combine(executablePath)
        hasher.combine(windowTitle)
        hasher.combine(capturedAtMillis)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFrontmostAppState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FrontmostAppState {
        return
            try FrontmostAppState(
                appName: FfiConverterString.read(from: &buf), 
                bundleId: FfiConverterOptionString.read(from: &buf), 
                executablePath: FfiConverterOptionString.read(from: &buf), 
                windowTitle: FfiConverterOptionString.read(from: &buf), 
                capturedAtMillis: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FrontmostAppState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.appName, into: &buf)
        FfiConverterOptionString.write(value.bundleId, into: &buf)
        FfiConverterOptionString.write(value.executablePath, into: &buf)
        FfiConverterOptionString.write(value.windowTitle, into: &buf)
        FfiConverterUInt64.write(value.capturedAtMillis, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrontmostAppState_lift(_ buf: RustBuffer) throws -> FrontmostAppState {
    return try FfiConverterTypeFrontmostAppState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrontmostAppState_lower(_ value: FrontmostAppState) -> RustBuffer {
    return FfiConverterTypeFrontmostAppState.lower(value)
}


public struct HostSnapshot {
    public var cpuPercent: Float
    public var memoryUsedBytes: UInt64
    public var memoryTotalBytes: UInt64
    public var swapUsedBytes: UInt64
    public var networkReceiveBps: UInt64
    public var networkSendBps: UInt64
    public var thermalState: String
    public var onBattery: Bool
    public var frontmostAppName: String?
    public var frontmostWindowTitle: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cpuPercent: Float, memoryUsedBytes: UInt64, memoryTotalBytes: UInt64, swapUsedBytes: UInt64, networkReceiveBps: UInt64, networkSendBps: UInt64, thermalState: String, onBattery: Bool, frontmostAppName: String?, frontmostWindowTitle: String?) {
        self.cpuPercent = cpuPercent
        self.memoryUsedBytes = memoryUsedBytes
        self.memoryTotalBytes = memoryTotalBytes
        self.swapUsedBytes = swapUsedBytes
        self.networkReceiveBps = networkReceiveBps
        self.networkSendBps = networkSendBps
        self.thermalState = thermalState
        self.onBattery = onBattery
        self.frontmostAppName = frontmostAppName
        self.frontmostWindowTitle = frontmostWindowTitle
    }
}



extension HostSnapshot: Equatable, Hashable {
    public static func ==(lhs: HostSnapshot, rhs: HostSnapshot) -> Bool {
        if lhs.cpuPercent != rhs.cpuPercent {
            return false
        }
        if lhs.memoryUsedBytes != rhs.memoryUsedBytes {
            return false
        }
        if lhs.memoryTotalBytes != rhs.memoryTotalBytes {
            return false
        }
        if lhs.swapUsedBytes != rhs.swapUsedBytes {
            return false
        }
        if lhs.networkReceiveBps != rhs.networkReceiveBps {
            return false
        }
        if lhs.networkSendBps != rhs.networkSendBps {
            return false
        }
        if lhs.thermalState != rhs.thermalState {
            return false
        }
        if lhs.onBattery != rhs.onBattery {
            return false
        }
        if lhs.frontmostAppName != rhs.frontmostAppName {
            return false
        }
        if lhs.frontmostWindowTitle != rhs.frontmostWindowTitle {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(cpuPercent)
        hasher.combine(memoryUsedBytes)
        hasher.combine(memoryTotalBytes)
        hasher.combine(swapUsedBytes)
        hasher.combine(networkReceiveBps)
        hasher.combine(networkSendBps)
        hasher.combine(thermalState)
        hasher.combine(onBattery)
        hasher.combine(frontmostAppName)
        hasher.combine(frontmostWindowTitle)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostSnapshot {
        return
            try HostSnapshot(
                cpuPercent: FfiConverterFloat.read(from: &buf), 
                memoryUsedBytes: FfiConverterUInt64.read(from: &buf), 
                memoryTotalBytes: FfiConverterUInt64.read(from: &buf), 
                swapUsedBytes: FfiConverterUInt64.read(from: &buf), 
                networkReceiveBps: FfiConverterUInt64.read(from: &buf), 
                networkSendBps: FfiConverterUInt64.read(from: &buf), 
                thermalState: FfiConverterString.read(from: &buf), 
                onBattery: FfiConverterBool.read(from: &buf), 
                frontmostAppName: FfiConverterOptionString.read(from: &buf), 
                frontmostWindowTitle: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HostSnapshot, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.cpuPercent, into: &buf)
        FfiConverterUInt64.write(value.memoryUsedBytes, into: &buf)
        FfiConverterUInt64.write(value.memoryTotalBytes, into: &buf)
        FfiConverterUInt64.write(value.swapUsedBytes, into: &buf)
        FfiConverterUInt64.write(value.networkReceiveBps, into: &buf)
        FfiConverterUInt64.write(value.networkSendBps, into: &buf)
        FfiConverterString.write(value.thermalState, into: &buf)
        FfiConverterBool.write(value.onBattery, into: &buf)
        FfiConverterOptionString.write(value.frontmostAppName, into: &buf)
        FfiConverterOptionString.write(value.frontmostWindowTitle, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSnapshot_lift(_ buf: RustBuffer) throws -> HostSnapshot {
    return try FfiConverterTypeHostSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSnapshot_lower(_ value: HostSnapshot) -> RustBuffer {
    return FfiConverterTypeHostSnapshot.lower(value)
}


public struct SystemSnapshot {
    public var sequence: UInt64
    public var capturedAtMillis: UInt64
    public var host: HostSnapshot
    public var capabilities: [CapabilitySnapshot]
    public var entities: [EntitySnapshot]
    public var timeline: [TimelineEvent]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sequence: UInt64, capturedAtMillis: UInt64, host: HostSnapshot, capabilities: [CapabilitySnapshot], entities: [EntitySnapshot], timeline: [TimelineEvent]) {
        self.sequence = sequence
        self.capturedAtMillis = capturedAtMillis
        self.host = host
        self.capabilities = capabilities
        self.entities = entities
        self.timeline = timeline
    }
}



extension SystemSnapshot: Equatable, Hashable {
    public static func ==(lhs: SystemSnapshot, rhs: SystemSnapshot) -> Bool {
        if lhs.sequence != rhs.sequence {
            return false
        }
        if lhs.capturedAtMillis != rhs.capturedAtMillis {
            return false
        }
        if lhs.host != rhs.host {
            return false
        }
        if lhs.capabilities != rhs.capabilities {
            return false
        }
        if lhs.entities != rhs.entities {
            return false
        }
        if lhs.timeline != rhs.timeline {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sequence)
        hasher.combine(capturedAtMillis)
        hasher.combine(host)
        hasher.combine(capabilities)
        hasher.combine(entities)
        hasher.combine(timeline)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSystemSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SystemSnapshot {
        return
            try SystemSnapshot(
                sequence: FfiConverterUInt64.read(from: &buf), 
                capturedAtMillis: FfiConverterUInt64.read(from: &buf), 
                host: FfiConverterTypeHostSnapshot.read(from: &buf), 
                capabilities: FfiConverterSequenceTypeCapabilitySnapshot.read(from: &buf), 
                entities: FfiConverterSequenceTypeEntitySnapshot.read(from: &buf), 
                timeline: FfiConverterSequenceTypeTimelineEvent.read(from: &buf)
        )
    }

    public static func write(_ value: SystemSnapshot, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.sequence, into: &buf)
        FfiConverterUInt64.write(value.capturedAtMillis, into: &buf)
        FfiConverterTypeHostSnapshot.write(value.host, into: &buf)
        FfiConverterSequenceTypeCapabilitySnapshot.write(value.capabilities, into: &buf)
        FfiConverterSequenceTypeEntitySnapshot.write(value.entities, into: &buf)
        FfiConverterSequenceTypeTimelineEvent.write(value.timeline, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSystemSnapshot_lift(_ buf: RustBuffer) throws -> SystemSnapshot {
    return try FfiConverterTypeSystemSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSystemSnapshot_lower(_ value: SystemSnapshot) -> RustBuffer {
    return FfiConverterTypeSystemSnapshot.lower(value)
}


public struct TimelineEvent {
    public var id: String
    public var timestampMillis: UInt64
    public var severity: TimelineSeverity
    public var entityId: String?
    public var title: String
    public var detail: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, timestampMillis: UInt64, severity: TimelineSeverity, entityId: String?, title: String, detail: String) {
        self.id = id
        self.timestampMillis = timestampMillis
        self.severity = severity
        self.entityId = entityId
        self.title = title
        self.detail = detail
    }
}



extension TimelineEvent: Equatable, Hashable {
    public static func ==(lhs: TimelineEvent, rhs: TimelineEvent) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.timestampMillis != rhs.timestampMillis {
            return false
        }
        if lhs.severity != rhs.severity {
            return false
        }
        if lhs.entityId != rhs.entityId {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.detail != rhs.detail {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(timestampMillis)
        hasher.combine(severity)
        hasher.combine(entityId)
        hasher.combine(title)
        hasher.combine(detail)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimelineEvent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimelineEvent {
        return
            try TimelineEvent(
                id: FfiConverterString.read(from: &buf), 
                timestampMillis: FfiConverterUInt64.read(from: &buf), 
                severity: FfiConverterTypeTimelineSeverity.read(from: &buf), 
                entityId: FfiConverterOptionString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                detail: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: TimelineEvent, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterUInt64.write(value.timestampMillis, into: &buf)
        FfiConverterTypeTimelineSeverity.write(value.severity, into: &buf)
        FfiConverterOptionString.write(value.entityId, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.detail, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimelineEvent_lift(_ buf: RustBuffer) throws -> TimelineEvent {
    return try FfiConverterTypeTimelineEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimelineEvent_lower(_ value: TimelineEvent) -> RustBuffer {
    return FfiConverterTypeTimelineEvent.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum CapabilityKind {
    
    case accessibility
    case fullDiskAccess
    case appleAutomation
    case chromiumDebug
    case dockerSocket
    case privilegedHelper
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCapabilityKind: FfiConverterRustBuffer {
    typealias SwiftType = CapabilityKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CapabilityKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .accessibility
        
        case 2: return .fullDiskAccess
        
        case 3: return .appleAutomation
        
        case 4: return .chromiumDebug
        
        case 5: return .dockerSocket
        
        case 6: return .privilegedHelper
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CapabilityKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .accessibility:
            writeInt(&buf, Int32(1))
        
        
        case .fullDiskAccess:
            writeInt(&buf, Int32(2))
        
        
        case .appleAutomation:
            writeInt(&buf, Int32(3))
        
        
        case .chromiumDebug:
            writeInt(&buf, Int32(4))
        
        
        case .dockerSocket:
            writeInt(&buf, Int32(5))
        
        
        case .privilegedHelper:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapabilityKind_lift(_ buf: RustBuffer) throws -> CapabilityKind {
    return try FfiConverterTypeCapabilityKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapabilityKind_lower(_ value: CapabilityKind) -> RustBuffer {
    return FfiConverterTypeCapabilityKind.lower(value)
}



extension CapabilityKind: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum CapabilityState {
    
    case unknown
    case granted
    case denied
    case requested
    case unavailable
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCapabilityState: FfiConverterRustBuffer {
    typealias SwiftType = CapabilityState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CapabilityState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .unknown
        
        case 2: return .granted
        
        case 3: return .denied
        
        case 4: return .requested
        
        case 5: return .unavailable
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CapabilityState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .unknown:
            writeInt(&buf, Int32(1))
        
        
        case .granted:
            writeInt(&buf, Int32(2))
        
        
        case .denied:
            writeInt(&buf, Int32(3))
        
        
        case .requested:
            writeInt(&buf, Int32(4))
        
        
        case .unavailable:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapabilityState_lift(_ buf: RustBuffer) throws -> CapabilityState {
    return try FfiConverterTypeCapabilityState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapabilityState_lower(_ value: CapabilityState) -> RustBuffer {
    return FfiConverterTypeCapabilityState.lower(value)
}



extension CapabilityState: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ComponentKind {
    
    case process
    case command
    case adapterContext
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeComponentKind: FfiConverterRustBuffer {
    typealias SwiftType = ComponentKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ComponentKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .process
        
        case 2: return .command
        
        case 3: return .adapterContext
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ComponentKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .process:
            writeInt(&buf, Int32(1))
        
        
        case .command:
            writeInt(&buf, Int32(2))
        
        
        case .adapterContext:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComponentKind_lift(_ buf: RustBuffer) throws -> ComponentKind {
    return try FfiConverterTypeComponentKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeComponentKind_lower(_ value: ComponentKind) -> RustBuffer {
    return FfiConverterTypeComponentKind.lower(value)
}



extension ComponentKind: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum EntityKind {
    
    case app
    case browser
    case daemon
    case terminalSession
    case service
    case unknown
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntityKind: FfiConverterRustBuffer {
    typealias SwiftType = EntityKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EntityKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .app
        
        case 2: return .browser
        
        case 3: return .daemon
        
        case 4: return .terminalSession
        
        case 5: return .service
        
        case 6: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EntityKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .app:
            writeInt(&buf, Int32(1))
        
        
        case .browser:
            writeInt(&buf, Int32(2))
        
        
        case .daemon:
            writeInt(&buf, Int32(3))
        
        
        case .terminalSession:
            writeInt(&buf, Int32(4))
        
        
        case .service:
            writeInt(&buf, Int32(5))
        
        
        case .unknown:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntityKind_lift(_ buf: RustBuffer) throws -> EntityKind {
    return try FfiConverterTypeEntityKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntityKind_lower(_ value: EntityKind) -> RustBuffer {
    return FfiConverterTypeEntityKind.lower(value)
}



extension EntityKind: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TimelineSeverity {
    
    case info
    case warning
    case critical
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTimelineSeverity: FfiConverterRustBuffer {
    typealias SwiftType = TimelineSeverity

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TimelineSeverity {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .info
        
        case 2: return .warning
        
        case 3: return .critical
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TimelineSeverity, into buf: inout [UInt8]) {
        switch value {
        
        
        case .info:
            writeInt(&buf, Int32(1))
        
        
        case .warning:
            writeInt(&buf, Int32(2))
        
        
        case .critical:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimelineSeverity_lift(_ buf: RustBuffer) throws -> TimelineSeverity {
    return try FfiConverterTypeTimelineSeverity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTimelineSeverity_lower(_ value: TimelineSeverity) -> RustBuffer {
    return FfiConverterTypeTimelineSeverity.lower(value)
}



extension TimelineSeverity: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCapabilitySnapshot: FfiConverterRustBuffer {
    typealias SwiftType = [CapabilitySnapshot]

    public static func write(_ value: [CapabilitySnapshot], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCapabilitySnapshot.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CapabilitySnapshot] {
        let len: Int32 = try readInt(&buf)
        var seq = [CapabilitySnapshot]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCapabilitySnapshot.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeComponentSnapshot: FfiConverterRustBuffer {
    typealias SwiftType = [ComponentSnapshot]

    public static func write(_ value: [ComponentSnapshot], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeComponentSnapshot.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ComponentSnapshot] {
        let len: Int32 = try readInt(&buf)
        var seq = [ComponentSnapshot]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeComponentSnapshot.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEntitySnapshot: FfiConverterRustBuffer {
    typealias SwiftType = [EntitySnapshot]

    public static func write(_ value: [EntitySnapshot], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEntitySnapshot.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [EntitySnapshot] {
        let len: Int32 = try readInt(&buf)
        var seq = [EntitySnapshot]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEntitySnapshot.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTimelineEvent: FfiConverterRustBuffer {
    typealias SwiftType = [TimelineEvent]

    public static func write(_ value: [TimelineEvent], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTimelineEvent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TimelineEvent] {
        let len: Int32 = try readInt(&buf)
        var seq = [TimelineEvent]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTimelineEvent.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_aetower_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_aetower_ffi_checksum_method_monitorengine_clear_frontmost_app_state() != 44857) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aetower_ffi_checksum_method_monitorengine_configure_chromium_endpoint() != 3795) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aetower_ffi_checksum_method_monitorengine_configure_docker_socket_path() != 15511) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aetower_ffi_checksum_method_monitorengine_configure_privileged_helper() != 57500) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aetower_ffi_checksum_method_monitorengine_latest_snapshot() != 64950) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aetower_ffi_checksum_method_monitorengine_set_capability_state() != 11556) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aetower_ffi_checksum_method_monitorengine_update_frontmost_app_state() != 57149) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_aetower_ffi_checksum_constructor_monitorengine_new() != 50482) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all